.PHONY: all

all:
	gcc -Wall -Wextra -pedantic -std=c17 -o test main.c
	
debug:
	gcc -g -gdwarf-5 -Wall -Wextra -pedantic -std=c17 -o test main.c

simulate_quiet: all
	./test 500 -q > results500_q.txt
	./test 2000 -q > results2000_q.txt
	./test 20000 -q > results20000_q.txt
	./test 32000 -q > results32000_q.txt
	
simulate: all
	./test 500 > results500.txt
	./test 2000 > results2000.txt
	./test 20000 > results20000.txt
	./test 32000 > results32000.txt
	
clean:
	rm test results*.txt

help:
	@echo "Type make simulate to simulate process creation with details,"\
	"make simulate_quiet to supress details, make to create "\
	"the program, or make clean to remove files generated by other targets."
